# Python Review 

Short review about some core concepts in Python exempolified by objects in the NumPy library. Goals:

- recall basic Python vocabulary
- practice markdown syntax

## Libraries and Packges
**library:** is a collection of the code that we can use to perform specific tasks in our programs. It can be a single file or multiple files.

**NumPy:**

- core library for numerical computing in Python
- many of libraries us NumPy arrays as their building blocks
- computations on NumPy objects are optimized for speed and memory usage

Let's import NumPy with its **standard abbreviations** `np`:

In [8]:
import numpy as np

(esc + press M -> convert code to markdown cell)

## Variables
**Variable:** a name we assign to a particular object in Python

Example:

In [2]:
# Assign a small array to variable a
a = np.array([[1,1,2],[3,5,8]])

To view a variable's value from our Jupyter notebook:

In [3]:
# Show the value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Print the value 
print(a)

[[1 1 2]
 [3 5 8]]


## Convention: Use `snake_case` for naming variables
This is the convention we will use in the course. Why? `my-variable` or `MyVariable` or `myVariable`,
PEP 8 - Style guide for Puthon Code recommends snake_case
It looks more professional when things are the same.

**Remember variable names should both be descriptive and consise!**

## Obejects

**objects,** informally, is a bundle of *properties* and *actions* about something specific.

Example:

Object: data frame 
Properties: number of rows, names of columns, and date created.
Actions: selecting a specific row or adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables.

object is thing and variable is what we name it. Like different languages have different words for same thing.

In practice, we often use the word variable and object interchangeably.

## Types

Every object in Python has a **type**, the type tells us what kind of object we have.
We can also call the type of an object, the **class** ob an object, both mean what kind of object we have.


In [5]:
print(a)


[[1 1 2]
 [3 5 8]]


In [6]:
# see the type/class of a variable/object by using the `type` function
type(a)

numpy.ndarray

In [9]:
np.ndarray

numpy.ndarray

The numpy.ndarray is the core object/data type of NumPy package. 

In [11]:
np.int64

numpy.int64

In [12]:
type(a[0,0])

numpy.int64

`numpy.int64` is not thej standard Python integer type `int`.

`numpy.int64` is a special data type in Numpy telling us that 1 is an integer stored as a 64-bit number

Check-in: access the value 5 in array `a`


In [15]:
#trying to get value five its going to be a[1,1] bc it is columns and rows so its the 2nd column 2n row and since its python 
#0 = 1

a[1,1]

5

## Functions

`print` was our first example of a python **function**

Functions take in a set of **arguements**, separated by commmas, and use those arguments to create an **output**.

In the course, we'll be using argument and parameter interchangable, but have slightly different meaning,
Arguement is the actual value you give to the function?

We can ask for info about what a function does by ? followed by the function name 

In [16]:
# Example 

?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


What we obtain is a **docstring**, a special type of comment that is used to document how a function (or a class, or module) works.

Notice that there are different types of arguments inside the function's parenthesis.

Roughly speaking, a function has two types of arguments:

- **non-optional arguments**: arguments *you* have to specify for the function to work
- **optional arguments**: arguments that are pre filled with a default value by the function, but you can override them. optional arguments appear inside the parenthesis () in the for `optional_arguments = default_value.`

Example

`end` is a parameter in `print` with default value a new line
We can pass the value `:-)` to this parameter so that it finishesd the line with `:-)` instead:


In [17]:
print('Change the end parameter', end= ':-)')

Change the end parameter:-)

## Attributes and methods

An object in python has attributes and methods.

- **attribute**: a property of the object, some piece of information about it, like length, weight of a dog.
- **method**: a procedure associated with an object, so it is an action where the main ingredient is the object itself, like a dog barks

## Check-in 

make a diagram like the cat one for a class `fish`. What are its attributes and methods

Example:

NumPy arrays have many methods and attributes. For example:

In [18]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [19]:
# T is an example of an attribute, it returns the transpose of array

print(a.T)

[[1 3]
 [1 5]
 [2 8]]


In [21]:
type(a.T)

numpy.ndarray

In [26]:
# Shape is another attribute that tells us the shape of the array

print(a.shape)

# its (2, 3) because two columns, three rows

print(type(a.shape))

(2, 3)
<class 'tuple'>


Attributes for the same object can have many different types

In [30]:
# ndim is an attribute holding the number of array dimensions
print('dim:', a.ndim, '| type:', type(a.ndim))

dim: 2 | type: <class 'int'>


Attributes can have many different data types.

Some examples of methods.


In [31]:
# The min method returns the minimum value in the array along a specified axis
print(a)
a.min(axis=0)

[[1 1 2]
 [3 5 8]]


array([1, 1, 2])

In [32]:
# Run min method with axis 
a.min()

1

Remember, methods are **functions** associated with an object. We can confirm this!

In [33]:
# method tolist() transform array into a list
a.tolist()

[[1, 1, 2], [3, 5, 8]]

In [34]:
type(a.tolist)

builtin_function_or_method

In [36]:
print(help)

Type help() for interactive help, or help(object) for help about object.


In [37]:
?help


Signature:   help(*args, **kwds)
Type:        _Helper
String form: Type help() for interactive help, or help(object) for help about object.
Namespace:   Python builtin
File:        /opt/anaconda3/lib/python3.9/_sitebuiltins.py
Docstring:  
Define the builtin 'help'.

This is a wrapper around pydoc.help that provides a helpful message
when 'help' is typed at the Python interactive prompt.

Calling help() at the Python prompt starts an interactive help session.
Calling help(thing) prints help for the python object 'thing'.


In [55]:
# read the print function help. What is the type of the arguement sep? is this optional?

In [57]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [50]:
value77 = 77
#the little aprostrophes so it knows its not an integer
stringvalue = '99'

In [51]:
print(value77, stringvalue, value77, sep= '%')

77%99%77
